module.exports = {
    specialties: [
        'Allergist',
        'Anesthesiologist',
        'Audiologist',
        'Cardiologist',
        'Chiropractor',
        'Dermatologist',
        'Endocrinologist',
        'Family Practitioner',
        'Gastroenterologist',
        'General Practitioner',
        'General Surgeon',
        'Gynecologist',
        'Hematologist',
        'Internist',
        'Neurologist',
        'Neurosurgeon',
        'Nutritionist',
        'Obstetrician',
        'Orthopedist',
        'Oncologist',
        'Pediatrician',
        'Plastic Surgeon',
        'Podiatrist',
        'Psychiatrist',
        'Psychologist',
        'Rheumatologist'
    ]
};
